forge "http://forge.puppetlabs.com"

mod "nefarioustim/user",
    :git => "git://github.com/nefarioustim/puppet-manifests.git",
    :path => "modules/user"

mod "nefarioustim/core-env",
    :git => "git://github.com/nefarioustim/puppet-manifests.git",
    :path => "modules/core-env"

mod "nefarioustim/redis",
    :git => "git://github.com/nefarioustim/puppet-manifests.git",
    :path => "modules/redis"

mod "nefarioustim/python",
    :git => "git://github.com/nefarioustim/puppet-manifests.git",
    :path => "modules/python"

mod "nefarioustim/supervisorprog",
    :git => "git://github.com/nefarioustim/puppet-manifests.git",
    :path => "modules/supervisorprog"
